server:
  port: 7003

spring:
  application:
    name: consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

service-url:
  nacos-user-service: http://provider-payment