server:
  port: 9004

spring:
  application:
    name: provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
management:
  endpoint:
    web:
      exposure:
        include: '*'